"""empty message

Revision ID: 24c659938f5a
Revises: 889e248bd509
Create Date: 2023-12-26 01:42:03.838523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c659938f5a'
down_revision = '889e248bd509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('worked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worked', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
