"""empty message

Revision ID: 481a01d667f3
Revises: 24c659938f5a
Create Date: 2023-12-26 04:31:29.659394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481a01d667f3'
down_revision = '24c659938f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mero')
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('mail',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('mail',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('mero',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mero', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mero_pkey')
    )
    # ### end Alembic commands ###
